language: ruby
rvm:
- 1.9.3
install:
- bundle install
script: bundle exec rake site:deploy
after_script: 
env:
  global:
  - GIT_NAME=jeeyeon-jang
  - GIT_EMAIL=graziosojy@gmail.com
  - secure: 0AsplwdzT6XTk2bLTs8lfRcZkN052PF9XB6o+8GWkQIozXD3ApAVn7Hm6caldaujZla9wraMPPVy2oAJrBEU79sVzO4K9kbXYVlOblspJhm6wm0Nsbc+OtVC150kqdglIwjDLtOAxY1LaMpU5Z2FkhSTeJiyOgj8aCSdTdEiud/ky0CLMTmeKkyLhsOKtxSn22WWIcWjx6PWr+hP1Yi1cH7AOjjgqKw96oAR4Wi+TgUPSdFT5GZDuLdutYk8+D4dWSDCTQikSsSxqTKWb9bOO/655qXLifjYgWQTLhxQgUtf1uyqek4XjN4r7AXxcP83huDyrd/pcypJQnWyMyiJnyfi/xZMYhOVlrOEJ9Laa+HU5EYfh3aQPaYweEknRcn1+lcKwd+ibi3REoP9y9e4ypi7r1LsW1D9QLAI0+xUK6DNjO/Keax+e2UBtPOat5HAIglouD/h7sRZ3IphZ2qmZCL/naYZRG9n6+kt6w2zOorB/wF5r/AIgV1B8gBujcNZZk5ydVrT75vse3/XVAWXcb3jgek8qXEsbwvq+mannrtw/nBXM934FPS7MgQUph36uKDL/qaChKn/bfp4kDyDaCVkvOEPts4lUdBGrCP8rT5Fd3P/tiQBsyuA+lRh/LQlkmln2th8voH7tiZVCpE3tFXvr6iDyo9kt7mP+bUpqtc=
